# Generated by Django 2.2.6 on 2019-11-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('challenge_file', models.FileField(upload_to='')),
                ('release_time', models.DateTimeField()),
            ],
        ),
    ]
